import {
  AddCircleIcon,
  AiBookIcon,
  AiBrain01Icon,
  AiChat01Icon,
  AlertCircleIcon,
  ArrowDown01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Attachment01Icon,
  Book02Icon,
  Briefcase01Icon,
  BubbleChatIcon,
  Building03Icon,
  Cancel01Icon,
  CheckmarkCircle02Icon,
  Clock01Icon,
  Download01Icon,
  File01Icon,
  File02Icon,
  Globe02Icon,
  Home03Icon,
  InformationCircleIcon,
  Link01Icon,
  Loading02Icon,
  MailOpen02Icon,
  NotebookIcon,
  Pdf01Icon,
  Search01Icon,
  Shield01Icon,
  SparklesIcon,
  Target02Icon,
  UserCircleIcon,
  UserGroupIcon,
  ViewIcon,
  WorkflowCircle01Icon,
  YurtIcon,
} from '@hugeicons/core-free-icons'

export const iconRegistry = {
  addCircle: AddCircleIcon,
  agent: AiBrain01Icon,
  aiBook: AiBookIcon,
  aiChat: AiChat01Icon,
  alert: AlertCircleIcon,
  arrowDown: ArrowDown01Icon,
  arrowRight: ArrowRight01Icon,
  arrowUp: ArrowUp01Icon,
  attachment: Attachment01Icon,
  briefcase: Briefcase01Icon,
  bubbleChat: BubbleChatIcon,
  building: Building03Icon,
  cancel: Cancel01Icon,
  check: CheckmarkCircle02Icon,
  clock: Clock01Icon,
  document: File01Icon,
  documentAlt: File02Icon,
  download: Download01Icon,
  filePdf: Pdf01Icon,
  globe: Globe02Icon,
  home: Home03Icon,
  info: InformationCircleIcon,
  link: Link01Icon,
  loading: Loading02Icon,
  mail: MailOpen02Icon,
  notebook: NotebookIcon,
  reference: Book02Icon,
  search: Search01Icon,
  shield: Shield01Icon,
  sparkles: SparklesIcon,
  target: Target02Icon,
  user: UserCircleIcon,
  users: UserGroupIcon,
  view: ViewIcon,
  workflow: WorkflowCircle01Icon,
  yurt: YurtIcon,
} as const

export type AppIconName = keyof typeof iconRegistry
